from flask import Flask, jsonify, request
import re

app = Flask(__name__)


# List of neutral words
neutral_words = [
    "drive",
    "motivated",
    "guide",
    "continue",
    "ethic",
    "choice",
    "excellent",
    "person",
    "confident",
    "resilient",
    "structured",
    "inflexible",
    "tech industry",
    "equity options",
    "is adventurous",
    "employees",
    "independent",
    "table tennis",
    "billiards table",
    "should",
    "challenging",
    "they",
    "their",
    "themselves",
    "self-assured",
    "energetic",
    "assertive",
    "aspiring",
    "courageous",
    "determined",
    "protective",
    "self-reliant",
    "influential",
    "expressive",
    "guiding force",
    "high-speed",
    "daring",
    "logical",
    "resolute",
    "committed",
    "expert",
    "impartial",
    "outstanding performer",
    "brag",
    "demanding",
    "bravery",
    "considerate",
    "innovative",
    "flexible",
    "select",
    "inquisitive",
    "outstanding",
    "adaptable",
    "handling multiple tasks",
    "well-being",
    "creative",
    "instinctive",
    "long-term planning",
    "tough",
    "aware of oneself",
    "ethical",
    "reliable",
    "current",
    "health program",
    "foster",
    "instruct",
    "reliable",
    "society",
    "assisting",
    "devoted",
    "passion",
    "relational",
    "link",
    "dedicate",
    "they",
    "concur",
    "understanding",
    "responsive",
    "loving",
    "experience",
    "assist",
    "work together",
    "truthful",
    "confidence",
    "comprehend",
    "sympathy",
    "contribute",
    "courteous",
    "considerate",
    "supportive",
    "their",
    "theirs",
    "themselves",
    "androgynous",
    "encourage",
    "collective",
    "expressive",
    "complimentable",
    "tender",
    "mutual",
    "connection",
    "humility",
    "agreeable",
    "silent",
    "empathy",
    "friendly",
    "leading",
    "produce",
    "fluent English speaker",
    "well-groomed appearance",
    "indigenous",
    "cultural alignment",
    "diverse",
    "clean-cut",
    "tidy hair",
    "expert",
    "subordinate",
    "easy task",
    "informal meeting",
    "personal inspiration",
    "tech-savvy",
    "supportive leadership",
    "community",
    "eastern",
    "avoid using",
    "english proficiency",
    "fluent",
    "unauthorized individuals",
    "indigenous Northern people",
    "hispanic",
    "latinx",
    "mobile worker",
    "inclusion list",
]


@app.route('/')
def home():
    data = {
        'message': 'Hello, Ashgan!'
    }
    return jsonify(data)


@app.route('/post', methods=['POST'])
def handle_post():
    data = request.get_json()  # Get the JSON data from the request

    # Process the data or perform any desired operations
    # For example, let's assume the JSON data contains a 'name' field
    text = data.get('text')
    return jsonify(text)
